### PR TITLE
Fix CAS ticket format to support allowed character set

### LINKED ISSUE #177: Problem with Service Tickets with mod_auth_cas
Despite the CAS protocol being quite relaxed on the character set allowed in a Service Tickets (describing it as opaque with acceptable length of at least 32 characters). the [mod_auth_cas](https://github.com/apereo/mod_auth_cas) Apache plugin (written by Apereo) is quite strict and only [accepts](https://github.com/apereo/mod_auth_cas/blob/9acbc6239f35f291d3b166f897bdda012adf5cea/src/mod_auth_cas.c#L743) dots, hyphens and alnums. As a result, when the extension issues an ST containing an underscore it breaks the CAS authentication. This is a relatively random behavior.

We've opened an [issue](https://github.com/apereo/mod_auth_cas/issues/222) for `mod_auth_cas` but we also want to open a discussion on whether it would be possible to not include underscores in the issued STs from the extension.

### PR DESCRIPTION
**Pull request by sachtouris**
Closes #177

### CODE REVIEW

File: src/main/java/org/keycloak/protocol/cas/endpoints/AbstractValidateEndpoint.java [hunk 1]
```diff
@@ -96,15 +99,23 @@ protected void checkTicket(String ticket, String prefix, boolean requireReauth)
         }
 
         boolean isReusable = ticket.startsWith(CASLoginProtocol.PROXY_GRANTING_TICKET_PREFIX);
-
-        String[] parsed = DOT.split(ticket.substring(prefix.length()), 3);
+        // Check if the ticket is hex encoded or using old method
+        String[] parsed;
+        if (ticket.substring(prefix.length()).contains("."))
```
Comment (jktcp) [inline src/main/java/org/keycloak/protocol/cas/endpoints/AbstractValidateEndpoint.java]: Extract `ticket.substring(prefix.length())` into a variable (named `ticketValue`, maybe?)

**Review by jktcp — DISMISSED** [review]
Do not create a new commit with changes, use amend.

File: src/main/java/org/keycloak/protocol/cas/endpoints/AbstractValidateEndpoint.java [hunk 2]
```diff
@@ -262,6 +273,16 @@ protected String persistedTicket(String redirectUriParam, String prefix)
         UserSessionModel userSession = clientSession.getUserSession();
         OAuth2Code codeData = new OAuth2Code(key, Time.currentTime() + userSession.getRealm().getAccessCodeLifespan(), null, null, redirectUriParam, null, null, null, userSession.getId());
         session.singleUseObjects().put(prefix + key, clientSession.getUserSession().getRealm().getAccessCodeLifespan(), codeData.serializeCode());
-        return prefix + key + "." + clientSession.getUserSession().getId() + "." + clientSession.getClient().getId();
+        return prefix + key + "--" + hexEncode(clientSession.getUserSession().getId()) + "--" + clientSession.getClient().getId();
+    }
+
+    private String hexEncode(String value) {
+        return HexFormat.of().formatHex(value.getBytes(StandardCharsets.UTF_8));
```
Comment (jacekkow) [inline src/main/java/org/keycloak/protocol/cas/endpoints/AbstractValidateEndpoint.java]: Use `US_ASCII` here and in hexDecode.

**Review by jacekkow — CHANGES_REQUESTED** [review]

File: src/main/java/org/keycloak/protocol/cas/endpoints/AbstractValidateEndpoint.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (sachtouris) [reply src/main/java/org/keycloak/protocol/cas/endpoints/AbstractValidateEndpoint.java]: You mean not to use if else condition and change implementation logic or change the brackets where they're getting placed?

**Review by jacekkow — CHANGES_REQUESTED** [review]
Only formatting issues left.
